imports:
    - { resource: security.yml }

parameters:
    locale: en

# Web Profile Configuration
web_profiler:
    toolbar: true
    intercept_redirects: false

# Symfony Framework Configuration
framework:
    secret: "%secret%"
    translator: { fallbacks: ["%locale%"] }
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
    session:
        handler_id: session.handler.native_file
        save_path:  "%kernel.root_dir%/../var/sessions/%kernel.environment%"
    assets:
        base_path: /web/

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"

# Doctrine Configuration
doctrine:
    dbal:
        driver:   pdo_mysql
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Sonata Block Configuration
sonata_block:
    default_contexts: [cms]
    blocks:
        sonata.admin.block.admin_list:
            contexts: [admin]

# Sonata Admin Configuration
sonata_admin:
    show_mosaic_button: false
    templates:
        layout: TopoAdminBundle::layout.html.twig
        user_block: TopoAdminBundle:Core:user_block.html.twig
