imports:

# Symfony Framework Configuration
framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

# Web Profile Configuration
web_profiler:
    toolbar: false
    intercept_redirects: false

# Swiftmailer Configuration
swiftmailer:
    disable_delivery: true
